#!/bin/bash
#This script generates the automatic labeler for the 3b1b/captions repository

languages=("german" "hebrew" "french" "spanish" "turkish" "hindi" "hungarian" "arabic" "bengali" "chinese" "croation" "indonesian" "italian" "japanese" "korean" "lithuanian" "marathi" "persian" "polish" "portuguese" "romanian" "russian" "serbian" "slovak" "thai" "ukranian" "vietnamese")

echo "# This file was automatically generated by the labeler_creator.sh script. Do not edit manually." > .github/labeler.yml

for language in "${languages[@]}"
do
    # Set the label name, with the first letter capitalized 
    label_name=$(echo $language | awk '{print toupper(substr($0, 1, 1)) tolower(substr($0, 2))}')
    echo "$label_name:" >> .github/labeler.yml
    echo "- changed-files:" >> .github/labeler.yml
    echo "  - */$language/*" >> .github/labeler.yml
    echo "" >> .github/labeler.yml
done




